### PR TITLE
add token to spec load

### PR DESCRIPTION
**Pull request by rinella**
I modified the loadSpec to send a token with the request so the swagger json can be filtered based on what a user has permission to in the api.  i was wondering what the use case is for multiple tokens and if this is something you would be interested in for the mainline.

thanks.

-Eric

### CODE REVIEW

**Comment by rinella** [comment]
reference issue #179

**Comment by mrin9** [comment]
Thanks for the PR, as I mentioned in #179 we have a different opinion on how we are going to approach operations with security.

We are unlikely to take this PR, 

but I still did a quick code-gaze, it looks all fine, However, I would have taken a reactive approach
 
For a small to mid sized spec, this approach may work fine, but for larger specs it may not cut the deal. From your code it seems like it will trigger a reload, parse of the whole spec, and after that will re-render of the whole app, 

I dont think a reload is necessary at all, we already have a parsed spec with us and the endpoints can be hidden/shown in a reactive manner based on which API keys are applied and which Endpoints can be used with the applied API Keys.

This is how the search functionality works, the Endpoints are hidden/shown based on the search text and its presence in the endpoint path

**Comment by rinella** [comment]
Thanks for checking it out.  Totally understand where you are coming from on the performance aspects.  

Our requirements are a little more security slanted.  We do not expose any endpoints unless you are authenticated.  The initial spec is empty.  Upon spec reload with the token in the request, the endpoints the user has access to are exposed.

**Comment by mrin9** [comment]
If you plan to update your fork, to hide/show endpoints reactively based on if an API key is applied, please consider a PR here. We do have plans to implement similar functionality to filter out operations based on various aspects like Security, Tags. We can use your PR and extend it to support some of our workflows

**Pull request closed without merging**
