### PR TITLE
Remove charset utf8

### PR DESCRIPTION
**Pull request by Uzlopak**
As discussed... Removing charset utf8 ;)

### CODE REVIEW

**Comment by ckeboss** [comment]
Should fix https://github.com/mrin9/RapiDoc/issues/248 :smiley:

**Comment by Uzlopak** [comment]
@ckeboss 

thank you... made the PR on my mobilephone and was to lazy to find the right issue :D

**Comment by mrin9** [comment]
Thanks for the PR !!!

**Comment by Uzlopak** [comment]
@mrin9 

Thank you for the fast merge. Will you release a new version please? Would be awesome, as it would make it fully usable for our use case.

Thank you

**Comment by mrin9** [comment]
next version release will be around mid of july.
meanwhile if you depend upon cdn to serve rapidoc, then you can pick it up from `dist` folder of github

**Pull request merged**
