### PR TITLE
Improve clarity of labels for anyOf & oneOf models

### PR DESCRIPTION
**Pull request by sneakyvv**
The labels are now using numeric keys, but if the schema has a `title` that can be used, which is clearer.

### Example schema
https://sneakyvv.github.io/RapiDoc/specs/oneof.json#/definitions/manager
& https://sneakyvv.github.io/RapiDoc/specs/oneof.json#/definitions/worker

### Current behavior
image

### Suggested new behavior
image
https://sneakyvv.github.io/RapiDoc/tests/simple-oneof.html#get-/one-of/employee

### Example schema
https://sneakyvv.github.io/RapiDoc/specs/anyof.json#/definitions/name
& https://sneakyvv.github.io/RapiDoc/specs/anyof.json#/definitions/job

### Current behavior
image

### Suggested new behavior
image
https://sneakyvv.github.io/RapiDoc/examples/anyof.html#get-/api/employee

### CODE REVIEW

**Comment by sneakyvv** [comment]
I would also suggest to use the `title` for primitives & use it as array key.
See https://sneakyvv.github.io/RapiDoc/examples/oneof-titles.html#get-/one-of/employee

#### Schema
https://sneakyvv.github.io/RapiDoc/specs/oneof-titles.json
```
"oneOf": [
    { "$ref": "#/components/schemas/manager" },
    { "$ref": "#/components/schemas/worker" },
    {
        "type": "object",
        "description": "this has no title",
        "properties": {
            "personnel number": { "type": "string" }
        }
    },
    {
        "type": "array",
        "title": "an array title",
        "items": { "type": "string", "title": "an array item" }
    },
    {
        "type": "array",
        "description": "array without title",
        "items": { "type": "string", "title": "an array item" }
    },
    { "type": "string", "title": "ID number" },
    { "type": "null" }
]
```

#### Before
image

#### After
image

**Comment by mrin9** [comment]
Thanks, this is a great PR !!!
Our UX has a minor feedback on styling these labels. They would like to keep the sequencing irrespective of the title. This will help provide clarity to users when there are mixed options some with title and some without.

Below is their suggested style.

Screen Shot 2020-11-17 at 9 20 07 AM

**Comment by sneakyvv** [comment]
The suggested style change has been applied. See the same examples from before:

- https://sneakyvv.github.io/RapiDoc/tests/simple-oneof.html#get-/one-of/employee
- https://sneakyvv.github.io/RapiDoc/examples/oneof-titles.html#get-/one-of/employee
- https://sneakyvv.github.io/RapiDoc/examples/anyof.html#get-/api/employee

**Comment by mrin9** [comment]
Thanks, LGTM... is under review by others 

> on a side note one of your previous PR  #350 have failed one of our test case, and may be pulled back

for instance https://sneakyvv.github.io/RapiDoc/tests/simple-oneof.html#get-/one-of/employee
example should be rendered as 

```js
[
  {
    id: "string",
    employee: {
      name: "string",
      directReports: 0
    }
  }
]
```

instead it is rendered as 
```js
[{
    id: "string",
    employee: {
      0: {
        name: "string",
        directReports: 0
      },
      1: {
        name: "string",
        managerName: "string"
       }
    }
}]
```

feel free if you intend to fix it as a part of separate PR else will revert it for now and someone will to work on it later to address the issues as a part of this PR

**Comment by sneakyvv** [comment]
@mrin9 PR #356 has been added to address the issue you mentioned.

**Review by mrin9 — APPROVED** [review]

**Comment by mrin9** [comment]
Thanks for your PR !!!

**Pull request merged**
